# Generated by Django 3.2.9 on 2021-12-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoProperties',
            fields=[
                ('model', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('class_field', models.IntegerField(db_column='class')),
            ],
            options={
                'db_table': 'auto_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_number', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField()),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sum', models.IntegerField()),
                ('departure_longitude', models.FloatField()),
                ('departure_latitude', models.FloatField()),
                ('arrival_longitude', models.FloatField()),
                ('arrival_latitude', models.FloatField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'payment_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=9)),
                ('model', models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, to='TaxiAgregator.autoproperties')),
            ],
            options={
                'db_table': 'auto',
                'managed': True,
            },
        ),
    ]
